// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package clientServer

import (
	"context"
	"fmt"
	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"
	"math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TransactionId struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionId) Reset()         { *m = TransactionId{} }
func (m *TransactionId) String() string { return proto.CompactTextString(m) }
func (*TransactionId) ProtoMessage()    {}
func (*TransactionId) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{1}
}

func (m *TransactionId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionId.Unmarshal(m, b)
}
func (m *TransactionId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionId.Marshal(b, m, deterministic)
}
func (m *TransactionId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionId.Merge(m, src)
}
func (m *TransactionId) XXX_Size() int {
	return xxx_messageInfo_TransactionId.Size(m)
}
func (m *TransactionId) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionId.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionId proto.InternalMessageInfo

func (m *TransactionId) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Status struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{2}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetParams struct {
	ServerIdentifier     string   `protobuf:"bytes,1,opt,name=server_identifier,json=serverIdentifier,proto3" json:"server_identifier,omitempty"`
	ObjectName           string   `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParams) Reset()         { *m = GetParams{} }
func (m *GetParams) String() string { return proto.CompactTextString(m) }
func (*GetParams) ProtoMessage()    {}
func (*GetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{3}
}

func (m *GetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParams.Unmarshal(m, b)
}
func (m *GetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParams.Marshal(b, m, deterministic)
}
func (m *GetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParams.Merge(m, src)
}
func (m *GetParams) XXX_Size() int {
	return xxx_messageInfo_GetParams.Size(m)
}
func (m *GetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetParams proto.InternalMessageInfo

func (m *GetParams) GetServerIdentifier() string {
	if m != nil {
		return m.ServerIdentifier
	}
	return ""
}

func (m *GetParams) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

type SetParams struct {
	ServerIdentifier     string   `protobuf:"bytes,1,opt,name=server_identifier,json=serverIdentifier,proto3" json:"server_identifier,omitempty"`
	ObjectName           string   `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	Value                string   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetParams) Reset()         { *m = SetParams{} }
func (m *SetParams) String() string { return proto.CompactTextString(m) }
func (*SetParams) ProtoMessage()    {}
func (*SetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_014de31d7ac8c57c, []int{4}
}

func (m *SetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetParams.Unmarshal(m, b)
}
func (m *SetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetParams.Marshal(b, m, deterministic)
}
func (m *SetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetParams.Merge(m, src)
}
func (m *SetParams) XXX_Size() int {
	return xxx_messageInfo_SetParams.Size(m)
}
func (m *SetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetParams proto.InternalMessageInfo

func (m *SetParams) GetServerIdentifier() string {
	if m != nil {
		return m.ServerIdentifier
	}
	return ""
}

func (m *SetParams) GetObjectName() string {
	if m != nil {
		return m.ObjectName
	}
	return ""
}

func (m *SetParams) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Transaction)(nil), "clientServer.Transaction")
	proto.RegisterType((*TransactionId)(nil), "clientServer.TransactionId")
	proto.RegisterType((*Status)(nil), "clientServer.Status")
	proto.RegisterType((*GetParams)(nil), "clientServer.GetParams")
	proto.RegisterType((*SetParams)(nil), "clientServer.SetParams")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor_014de31d7ac8c57c) }

var fileDescriptor_014de31d7ac8c57c = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x91, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x9b, 0x88, 0x91, 0x4c, 0x55, 0x74, 0x28, 0x18, 0x0b, 0x52, 0xd9, 0x93, 0x20, 0xe4,
	0xa0, 0x57, 0x2f, 0xe2, 0xa1, 0xf4, 0x22, 0x62, 0xbc, 0x78, 0x2a, 0xd3, 0x64, 0x94, 0x95, 0x66,
	0x57, 0x76, 0xa7, 0x7d, 0x07, 0xdf, 0x5a, 0xd8, 0xa4, 0x21, 0x9a, 0x73, 0x8f, 0xff, 0x7c, 0xf3,
	0x27, 0xcb, 0x37, 0x70, 0x5c, 0xae, 0x35, 0x1b, 0xc9, 0xbf, 0x9d, 0x15, 0x8b, 0x6d, 0x2a, 0xd8,
	0x6d, 0xd9, 0xa9, 0x2b, 0x18, 0xbf, 0x39, 0x32, 0x9e, 0x4a, 0xd1, 0xd6, 0xe0, 0x29, 0xc4, 0xba,
	0xca, 0xa2, 0xeb, 0xe8, 0x26, 0x7d, 0x8d, 0x75, 0xa5, 0x66, 0x70, 0xd2, 0xc3, 0x8b, 0x6a, 0xb0,
	0xa0, 0x20, 0x29, 0x84, 0x64, 0xe3, 0x31, 0x83, 0xa3, 0x9a, 0xbd, 0xa7, 0x4f, 0x6e, 0xf1, 0x2e,
	0xaa, 0x77, 0x48, 0xe7, 0x2c, 0x2f, 0xe4, 0xa8, 0xf6, 0x78, 0x0b, 0xe7, 0x3e, 0xfc, 0x7a, 0xa9,
	0x2b, 0x36, 0xa2, 0x3f, 0x34, 0xbb, 0xb6, 0x70, 0xd6, 0x80, 0x45, 0x37, 0xc7, 0x19, 0x8c, 0xed,
	0xea, 0x8b, 0x4b, 0x59, 0x1a, 0xaa, 0x39, 0x8b, 0xc3, 0x1a, 0x34, 0xa3, 0x67, 0xaa, 0x59, 0x59,
	0x48, 0x8b, 0xfd, 0x7c, 0x1a, 0x27, 0x70, 0xb8, 0xa5, 0xf5, 0x86, 0xb3, 0x83, 0x80, 0x9a, 0x70,
	0xf7, 0x13, 0x41, 0xd2, 0xa8, 0xc3, 0x07, 0x48, 0x9f, 0x5a, 0x95, 0x82, 0x17, 0x79, 0x5f, 0x6b,
	0xde, 0x3d, 0x6a, 0x3a, 0xf9, 0x07, 0x82, 0x2c, 0x35, 0xc2, 0xc7, 0x5d, 0x7b, 0x3e, 0x6c, 0x77,
	0xb6, 0xa6, 0x97, 0x7f, 0x41, 0xef, 0x16, 0x6a, 0xb4, 0x4a, 0xc2, 0x41, 0xef, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x46, 0xa6, 0x9b, 0xf6, 0xe0, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerClient interface {
	ClientSet(ctx context.Context, in *SetParams, opts ...grpc.CallOption) (*Status, error)
	ClientGet(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*Transaction, error)
}

type serverClient struct {
	cc *grpc.ClientConn
}

func NewServerClient(cc *grpc.ClientConn) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) ClientSet(ctx context.Context, in *SetParams, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/clientServer.Server/ClientSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) ClientGet(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/clientServer.Server/ClientGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
type ServerServer interface {
	ClientSet(context.Context, *SetParams) (*Status, error)
	ClientGet(context.Context, *GetParams) (*Transaction, error)
}

// UnimplementedServerServer can be embedded to have forward compatible implementations.


func RegisterServerServer(s *grpc.Server, srv ServerServer) {
	s.RegisterService(&_Server_serviceDesc, srv)
}

func _Server_ClientSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).ClientSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clientServer.Server/ClientSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).ClientSet(ctx, req.(*SetParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_ClientGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).ClientGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/clientServer.Server/ClientGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).ClientGet(ctx, req.(*GetParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Server_serviceDesc = grpc.ServiceDesc{
	ServiceName: "clientServer.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientSet",
			Handler:    _Server_ClientSet_Handler,
		},
		{
			MethodName: "ClientGet",
			Handler:    _Server_ClientGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "client.proto",
}
