// Code generated by protoc-gen-go. DO NOT EDIT.
// source: coordinator.proto

//protoc -I . *.proto --go_out=plugins=grpc:.

package protos

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReportParam struct {
	FromServer           *string  `protobuf:"bytes,1,req,name=fromServer" json:"fromServer,omitempty"`
	ToServer             *string  `protobuf:"bytes,2,req,name=toServer" json:"toServer,omitempty"`
	IsOn                 *bool    `protobuf:"varint,3,req,name=isOn" json:"isOn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportParam) Reset()         { *m = ReportParam{} }
func (m *ReportParam) String() string { return proto.CompactTextString(m) }
func (*ReportParam) ProtoMessage()    {}
func (*ReportParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_99e779eb11ceee19, []int{0}
}

func (m *ReportParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportParam.Unmarshal(m, b)
}
func (m *ReportParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportParam.Marshal(b, m, deterministic)
}
func (m *ReportParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportParam.Merge(m, src)
}
func (m *ReportParam) XXX_Size() int {
	return xxx_messageInfo_ReportParam.Size(m)
}
func (m *ReportParam) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportParam.DiscardUnknown(m)
}

var xxx_messageInfo_ReportParam proto.InternalMessageInfo

func (m *ReportParam) GetFromServer() string {
	if m != nil && m.FromServer != nil {
		return *m.FromServer
	}
	return ""
}

func (m *ReportParam) GetToServer() string {
	if m != nil && m.ToServer != nil {
		return *m.ToServer
	}
	return ""
}

func (m *ReportParam) GetIsOn() bool {
	if m != nil && m.IsOn != nil {
		return *m.IsOn
	}
	return false
}

func init() {
	proto.RegisterType((*ReportParam)(nil), "protos.ReportParam")
}

func init() { proto.RegisterFile("coordinator.proto", fileDescriptor_99e779eb11ceee19) }

var fileDescriptor_99e779eb11ceee19 = []byte{
	// 244 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0x3d, 0x4b, 0xc4, 0x40,
	0x10, 0x3d, 0xa3, 0xc8, 0x39, 0xa7, 0x98, 0x1b, 0x9b, 0x90, 0x42, 0x8e, 0x54, 0x57, 0x5d, 0x21,
	0xa8, 0x85, 0x95, 0x44, 0x6d, 0x4f, 0xa2, 0xad, 0xc5, 0xde, 0x66, 0x84, 0xa0, 0x3b, 0xb3, 0xcc,
	0xae, 0xc2, 0xfd, 0x32, 0xff, 0x9e, 0x90, 0x78, 0x26, 0x45, 0x10, 0xac, 0x76, 0xdf, 0xd7, 0xee,
	0xe3, 0xc1, 0xdc, 0x8a, 0x68, 0xdd, 0xb0, 0x89, 0xa2, 0x2b, 0xaf, 0x12, 0x05, 0x0f, 0xdb, 0x23,
	0xe4, 0xc7, 0x56, 0x9c, 0x13, 0xee, 0xd8, 0xe2, 0x05, 0x66, 0x15, 0x79, 0xd1, 0xf8, 0x68, 0xd4,
	0x38, 0x3c, 0x07, 0x78, 0x55, 0x71, 0x4f, 0xa4, 0x9f, 0xa4, 0xd9, 0xde, 0x22, 0x59, 0x1e, 0x55,
	0x03, 0x06, 0x73, 0x98, 0x46, 0xf9, 0x51, 0x93, 0x56, 0xfd, 0xc5, 0x88, 0x70, 0xd0, 0x84, 0x35,
	0x67, 0xfb, 0x8b, 0x64, 0x39, 0xad, 0xda, 0xfb, 0xc5, 0x57, 0x02, 0xb3, 0xb2, 0xaf, 0x82, 0xd7,
	0x70, 0xba, 0xf6, 0xc4, 0xcf, 0x6a, 0x38, 0x18, 0x1b, 0x1b, 0x61, 0x3c, 0xe9, 0x9a, 0x84, 0xd5,
	0xbd, 0xf3, 0x71, 0x9b, 0x9f, 0xed, 0xe0, 0xc0, 0x53, 0x4c, 0xf0, 0x06, 0xd2, 0xf2, 0x5d, 0x02,
	0x0d, 0x93, 0x63, 0xd6, 0x3c, 0xdd, 0x91, 0x0f, 0x44, 0xf5, 0xc6, 0xd8, 0xb7, 0x62, 0x82, 0x57,
	0x30, 0x2f, 0xc5, 0xb9, 0x26, 0xfe, 0xf1, 0xef, 0x58, 0xee, 0x12, 0xd2, 0xdb, 0x8d, 0xe8, 0x7f,
	0x63, 0x25, 0x64, 0xdd, 0xa6, 0x15, 0x05, 0xf9, 0x50, 0x4b, 0x77, 0xe4, 0x89, 0x6b, 0x62, 0xbb,
	0xed, 0x3b, 0x0f, 0x56, 0x1f, 0x7b, 0xe4, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x44, 0x35, 0x3d, 0xe7,
	0xc2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoordinatorClient interface {
	OpenTransaction(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Transaction, error)
	CloseTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Feedback, error)
	CommitTransaction(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Feedback, error)
	AbortTransaction(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Feedback, error)
	ReportResourceDependency(ctx context.Context, in *ReportParam, opts ...grpc.CallOption) (*Feedback, error)
}

type coordinatorClient struct {
	cc *grpc.ClientConn
}

func NewCoordinatorClient(cc *grpc.ClientConn) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) OpenTransaction(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, "/protos.Coordinator/OpenTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) CloseTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/protos.Coordinator/CloseTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) CommitTransaction(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/protos.Coordinator/CommitTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) AbortTransaction(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/protos.Coordinator/AbortTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) ReportResourceDependency(ctx context.Context, in *ReportParam, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/protos.Coordinator/ReportResourceDependency", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServer is the server API for Coordinator service.
type CoordinatorServer interface {
	OpenTransaction(context.Context, *Empty) (*Transaction, error)
	CloseTransaction(context.Context, *Transaction) (*Feedback, error)
	CommitTransaction(context.Context, *Empty) (*Feedback, error)
	AbortTransaction(context.Context, *Empty) (*Feedback, error)
	ReportResourceDependency(context.Context, *ReportParam) (*Feedback, error)
}

// UnimplementedCoordinatorServer can be embedded to have forward compatible implementations.
type UnimplementedCoordinatorServer struct {
}

func (*UnimplementedCoordinatorServer) OpenTransaction(ctx context.Context, req *Empty) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenTransaction not implemented")
}
func (*UnimplementedCoordinatorServer) CloseTransaction(ctx context.Context, req *Transaction) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CloseTransaction not implemented")
}
func (*UnimplementedCoordinatorServer) CommitTransaction(ctx context.Context, req *Empty) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (*UnimplementedCoordinatorServer) AbortTransaction(ctx context.Context, req *Empty) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortTransaction not implemented")
}
func (*UnimplementedCoordinatorServer) ReportResourceDependency(ctx context.Context, req *ReportParam) (*Feedback, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportResourceDependency not implemented")
}

func RegisterCoordinatorServer(s *grpc.Server, srv CoordinatorServer) {
	s.RegisterService(&_Coordinator_serviceDesc, srv)
}

func _Coordinator_OpenTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).OpenTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Coordinator/OpenTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).OpenTransaction(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_CloseTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).CloseTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Coordinator/CloseTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).CloseTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Coordinator/CommitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).CommitTransaction(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_AbortTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).AbortTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Coordinator/AbortTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).AbortTransaction(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_ReportResourceDependency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).ReportResourceDependency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Coordinator/ReportResourceDependency",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).ReportResourceDependency(ctx, req.(*ReportParam))
	}
	return interceptor(ctx, in, info, handler)
}

var _Coordinator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OpenTransaction",
			Handler:    _Coordinator_OpenTransaction_Handler,
		},
		{
			MethodName: "CloseTransaction",
			Handler:    _Coordinator_CloseTransaction_Handler,
		},
		{
			MethodName: "CommitTransaction",
			Handler:    _Coordinator_CommitTransaction_Handler,
		},
		{
			MethodName: "AbortTransaction",
			Handler:    _Coordinator_AbortTransaction_Handler,
		},
		{
			MethodName: "ReportResourceDependency",
			Handler:    _Coordinator_ReportResourceDependency_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coordinator.proto",
}
