// This file was automatically generated by genny.
// Any changes will be lost if this file is regenerated.
// see https://github.com/cheekybits/genny

package server

import "sync"

// cat generic_ccmap.go | genny gen "String=string String=*blockchain.Transaction" > [targetName].go

// StringDictionary the set of Items
type DependencyMap struct {
	items map[string]string
	lock  sync.RWMutex
}

// Set adds a new item to the ccmap
func (d *DependencyMap) Set(k string, v string) {
	d.lock.Lock()
	defer d.lock.Unlock()
	if d.items == nil {
		d.items = make(map[string]string)
	}
	d.items[k] = v
}

// Delete removes a value from the ccmap, given its key
func (d *DependencyMap) Delete(k string) bool {
	d.lock.Lock()
	defer d.lock.Unlock()
	_, ok := d.items[k]
	if ok {
		delete(d.items, k)
	}
	return ok
}

// Has returns true if the key exists in the ccmap
func (d *DependencyMap) Has(k string) bool {
	d.lock.RLock()
	defer d.lock.RUnlock()
	_, ok := d.items[k]
	return ok
}

// Get returns the value associated with the key
func (d *DependencyMap) Get(k string) string {
	d.lock.RLock()
	defer d.lock.RUnlock()
	return d.items[k]
}

// Clear removes all the items from the ccmap
func (d *DependencyMap) Clear() {
	d.lock.Lock()
	defer d.lock.Unlock()
	d.items = make(map[string]string)
}

// Size returns the amount of elements in the ccmap
func (d *DependencyMap) Size() int {
	d.lock.RLock()
	defer d.lock.RUnlock()
	return len(d.items)
}

// Strings returns a slice of all the keys present
func (d *DependencyMap) GetKys() []string {
	d.lock.RLock()
	defer d.lock.RUnlock()
	keys := []string{}
	for i := range d.items {
		keys = append(keys, i)
	}
	return keys
}

// Strings returns a slice of all the values present
func (d *DependencyMap) GetVals() []string {
	d.lock.RLock()
	defer d.lock.RUnlock()
	values := []string{}
	for i := range d.items {
		values = append(values, d.items[i])
	}
	return values
}
