// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package server

import (
	"context"
	"fmt"
	"github.com/golang/protobuf/proto"
	"google.golang.org/grpc"
	"math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetParams struct {
	TransactionID        *string  `protobuf:"bytes,1,req,name=transactionID" json:"transactionID,omitempty"`
	ServerIdentifier     *string  `protobuf:"bytes,2,req,name=server_identifier,json=serverIdentifier" json:"server_identifier,omitempty"`
	ObjectName           *string  `protobuf:"bytes,3,req,name=object_name,json=objectName" json:"object_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetParams) Reset()         { *m = GetParams{} }
func (m *GetParams) String() string { return proto.CompactTextString(m) }
func (*GetParams) ProtoMessage()    {}
func (*GetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *GetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetParams.Unmarshal(m, b)
}
func (m *GetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetParams.Marshal(b, m, deterministic)
}
func (m *GetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetParams.Merge(m, src)
}
func (m *GetParams) XXX_Size() int {
	return xxx_messageInfo_GetParams.Size(m)
}
func (m *GetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetParams proto.InternalMessageInfo

func (m *GetParams) GetTransactionID() string {
	if m != nil && m.TransactionID != nil {
		return *m.TransactionID
	}
	return ""
}

func (m *GetParams) GetServerIdentifier() string {
	if m != nil && m.ServerIdentifier != nil {
		return *m.ServerIdentifier
	}
	return ""
}

func (m *GetParams) GetObjectName() string {
	if m != nil && m.ObjectName != nil {
		return *m.ObjectName
	}
	return ""
}

type SetParams struct {
	TransactionID        *string  `protobuf:"bytes,1,req,name=transactionID" json:"transactionID,omitempty"`
	ServerIdentifier     *string  `protobuf:"bytes,2,req,name=server_identifier,json=serverIdentifier" json:"server_identifier,omitempty"`
	ObjectName           *string  `protobuf:"bytes,3,req,name=object_name,json=objectName" json:"object_name,omitempty"`
	Value                *string  `protobuf:"bytes,4,req,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetParams) Reset()         { *m = SetParams{} }
func (m *SetParams) String() string { return proto.CompactTextString(m) }
func (*SetParams) ProtoMessage()    {}
func (*SetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *SetParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetParams.Unmarshal(m, b)
}
func (m *SetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetParams.Marshal(b, m, deterministic)
}
func (m *SetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetParams.Merge(m, src)
}
func (m *SetParams) XXX_Size() int {
	return xxx_messageInfo_SetParams.Size(m)
}
func (m *SetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SetParams.DiscardUnknown(m)
}

var xxx_messageInfo_SetParams proto.InternalMessageInfo

func (m *SetParams) GetTransactionID() string {
	if m != nil && m.TransactionID != nil {
		return *m.TransactionID
	}
	return ""
}

func (m *SetParams) GetServerIdentifier() string {
	if m != nil && m.ServerIdentifier != nil {
		return *m.ServerIdentifier
	}
	return ""
}

func (m *SetParams) GetObjectName() string {
	if m != nil && m.ObjectName != nil {
		return *m.ObjectName
	}
	return ""
}

func (m *SetParams) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*GetParams)(nil), "protos.GetParams")
	proto.RegisterType((*SetParams)(nil), "protos.SetParams")
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7) }

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x90, 0xbf, 0x4a, 0x03, 0x41,
	0x10, 0xc6, 0xbd, 0x18, 0x85, 0x1b, 0x15, 0xee, 0x46, 0x8b, 0x23, 0x8d, 0x72, 0x58, 0x08, 0x42,
	0x8a, 0xb4, 0xda, 0x48, 0xc4, 0x23, 0x4d, 0x10, 0x63, 0x1f, 0xe6, 0xee, 0x46, 0x58, 0xcd, 0xee,
	0xc8, 0xee, 0x98, 0xd6, 0xa7, 0xf0, 0x21, 0x7d, 0x0b, 0xe1, 0x96, 0xfc, 0x11, 0xc4, 0xc2, 0xc6,
	0x6a, 0xd9, 0xdf, 0xf7, 0xfd, 0xe0, 0xdb, 0x05, 0x70, 0xd2, 0xf2, 0xf0, 0xd5, 0x8b, 0x0a, 0xee,
	0x77, 0x47, 0x18, 0x1c, 0x36, 0x62, 0xad, 0xb8, 0x48, 0xcb, 0x77, 0x48, 0x2b, 0xd6, 0x7b, 0xf2,
	0x64, 0x03, 0x9e, 0xc3, 0x91, 0x7a, 0x72, 0x81, 0x1a, 0x35, 0xe2, 0x26, 0xb7, 0x45, 0x72, 0xd6,
	0xbb, 0x48, 0x1f, 0xbe, 0x43, 0xbc, 0x84, 0x3c, 0xb0, 0x5f, 0xb2, 0x9f, 0x9b, 0x96, 0x9d, 0x9a,
	0x27, 0xc3, 0xbe, 0xe8, 0x75, 0xcd, 0x2c, 0x06, 0x93, 0x35, 0xc7, 0x53, 0x38, 0x90, 0xfa, 0x99,
	0x1b, 0x9d, 0x3b, 0xb2, 0x5c, 0xec, 0x76, 0x35, 0x88, 0x68, 0x4a, 0x96, 0xcb, 0x8f, 0x04, 0xd2,
	0xd9, 0x7f, 0x2e, 0xc0, 0x13, 0xd8, 0x5b, 0xd2, 0xe2, 0x8d, 0x8b, 0x7e, 0x17, 0xc5, 0xcb, 0xe8,
	0x33, 0x81, 0xfe, 0x54, 0x5a, 0xc6, 0x11, 0xa4, 0xe3, 0x85, 0x61, 0xa7, 0x33, 0x56, 0xcc, 0xe3,
	0xb7, 0x85, 0xe1, 0x7a, 0xf2, 0x20, 0x5b, 0xa1, 0x3b, 0xe6, 0xb6, 0xa6, 0xe6, 0xa5, 0xdc, 0xd9,
	0x38, 0xd5, 0xb6, 0x53, 0xfd, 0xea, 0x5c, 0x43, 0x3e, 0x16, 0x6b, 0x8d, 0x3e, 0x6e, 0xde, 0x8a,
	0xc7, 0xab, 0xe2, 0x16, 0xfc, 0xd1, 0xbe, 0x82, 0xec, 0xa6, 0x16, 0xff, 0x27, 0xf9, 0x2b, 0x00,
	0x00, 0xff, 0xff, 0x19, 0x8f, 0x92, 0xce, 0x27, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	ClientSet(ctx context.Context, in *SetParams, opts ...grpc.CallOption) (*Feedback, error)
	ClientGet(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*Feedback, error)
	CommitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Feedback, error)
	AbortTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Feedback, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) ClientSet(ctx context.Context, in *SetParams, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/protos.Node/ClientSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) ClientGet(ctx context.Context, in *GetParams, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/protos.Node/ClientGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) CommitTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/protos.Node/CommitTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeClient) AbortTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*Feedback, error) {
	out := new(Feedback)
	err := c.cc.Invoke(ctx, "/protos.Node/AbortTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

//// UnimplementedNodeServer can be embedded to have forward compatible implementations.
//type UnimplementedNodeServer struct {
//}
//
//func (*UnimplementedNodeServer) ClientSet(ctx context.Context, req *SetParams) (*Feedback, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method ClientSet not implemented")
//}
//func (*UnimplementedNodeServer) ClientGet(ctx context.Context, req *GetParams) (*Feedback, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method ClientGet not implemented")
//}
//func (*UnimplementedNodeServer) CommitTransaction(ctx context.Context, req *Transaction) (*Feedback, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method CommitTransaction not implemented")
//}
//func (*UnimplementedNodeServer) AbortTransaction(ctx context.Context, req *Transaction) (*Feedback, error) {
//	return nil, status.Errorf(codes.Unimplemented, "method AbortTransaction not implemented")
//}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_ClientSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ClientSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Node/ClientSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ClientSet(ctx, req.(*SetParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_ClientGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).ClientGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Node/ClientGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).ClientGet(ctx, req.(*GetParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Node/CommitTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).CommitTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _Node_AbortTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).AbortTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Node/AbortTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).AbortTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClientSet",
			Handler:    _Node_ClientSet_Handler,
		},
		{
			MethodName: "ClientGet",
			Handler:    _Node_ClientGet_Handler,
		},
		{
			MethodName: "CommitTransaction",
			Handler:    _Node_CommitTransaction_Handler,
		},
		{
			MethodName: "AbortTransaction",
			Handler:    _Node_AbortTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "node.proto",
}
